#!/bin/bash

# Install/update a dedicated user systemd indiserver service for a ZWO ASI678MC.
# This does not modify indi-allsky capture runtime or the existing indiserver
# service generated by setup.sh.

set -o errexit
set -o nounset
set -o pipefail

SERVICE_NAME="${INDIALLSKY_ASI_SERVICE_NAME:-indiserver-asi678mc.service}"
INDI_PORT="${INDIALLSKY_ASI_INDI_PORT:-7625}"
INDI_DRIVER="${INDIALLSKY_ASI_INDI_DRIVER:-indi_asi_ccd}"
INDI_SOCKET="${INDIALLSKY_ASI_INDI_SOCKET:-/tmp/indiserver-modern-admin-7625}"
SYSTEMD_USER_DIR="${HOME}/.config/systemd/user"

if [ -f "/usr/local/bin/indiserver" ]; then
    INDISERVER="/usr/local/bin/indiserver"
elif [ -f "/usr/bin/indiserver" ]; then
    INDISERVER="/usr/bin/indiserver"
elif command -v indiserver >/dev/null 2>&1; then
    INDISERVER="$(command -v indiserver)"
else
    echo "ERROR: indiserver was not found in PATH, /usr/bin, or /usr/local/bin" >&2
    exit 1
fi

if ! command -v "$INDI_DRIVER" >/dev/null 2>&1; then
    if [ ! -x "$(dirname "$INDISERVER")/$INDI_DRIVER" ]; then
        echo "ERROR: INDI driver not found: $INDI_DRIVER" >&2
        exit 1
    fi
fi

mkdir -p "$SYSTEMD_USER_DIR"

cat > "$SYSTEMD_USER_DIR/$SERVICE_NAME" <<EOF
[Unit]
Description=Indi Server ASI678MC
After=network.target
Before=indi-allsky.service

[Service]
ExecStart=$INDISERVER -v -p $INDI_PORT -u $INDI_SOCKET indi_simulator_telescope $INDI_DRIVER
ExecStop=/bin/kill -TERM \$MAINPID
Restart=on-failure
RestartSec=5
UMask=0022

[Install]
WantedBy=default.target
EOF

chmod 644 "$SYSTEMD_USER_DIR/$SERVICE_NAME"

echo "Installed/updated $SYSTEMD_USER_DIR/$SERVICE_NAME"
echo
echo "Next commands:"
echo "  systemctl --user daemon-reload"
echo "  systemctl --user enable --now $SERVICE_NAME"
echo "  systemctl --user status $SERVICE_NAME --no-pager"
echo
echo "Effective command:"
echo "  $INDISERVER -v -p $INDI_PORT -u $INDI_SOCKET indi_simulator_telescope $INDI_DRIVER"
