#!/usr/bin/env python3
"""Run the Hybrid regression in an isolated runtime checkout, never deploy it.

The Python integration tests require the project's Linux dependencies and
/etc/indi-allsky/flask.json. They create their own isolated databases/fixtures.
Native browser and live hardware acceptance are separate from this suite.
Use --list to inspect the exact commands without running tests.
"""

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
import time


EXTRA_TESTS = (
    'generation_result_test.py', 'capture_profiles_test.py',
    'capture_timeout_policy_test.py', 'sftp_adapter_test.py',
    'modern_safe_action_test.py', 'full_config_parser_parity_test.py',
    'product_view_models_test.py', 'product_spine_regression_test.py',
    'auto_gain_controller_test.py', 'auto_gain_runtime_state_test.py',
    'auto_exposure_controller_test.py', 'legacy_auto_gain_steps_test.py',
    'network_commands_test.py', 'network_activation_polling_test.py',
    'network_scan_effects_test.py', 'focus_frames_test.py',
    'multicamera_processor_isolation_test.py', 'stretch_multicamera_mask_test.py',
)


def discover(root, python, oauth_python, node):
    paths = set(root.glob('testing/modern_admin_*_test.py'))
    paths.update(root.glob('testing/hybrid_*_test.py'))
    paths.discard(root / 'testing/hybrid_ui_acceptance_test.py')
    paths.update(root / 'testing' / name for name in EXTRA_TESTS)
    cases = [
        {'case': str(p.relative_to(root)), 'command': [
            oauth_python if p.name == 'hybrid_youtube_flow_test.py' else python,
            str(p),
        ]}
        for p in sorted(paths)
    ]
    cases.extend([
        {'case': 'hybrid_archive_flow_test.py:library', 'command': [
            python, str(root / 'testing/hybrid_archive_flow_test.py'),
            '--entrypoint', 'library',
        ]},
        {'case': 'compileall', 'command': [
            python, '-m', 'compileall', '-q', str(root / 'indi_allsky'),
        ]},
    ])
    cases.extend({'case': str(p.relative_to(root)), 'command': [node, str(p)]}
                 for p in sorted(root.glob('testing/hybrid_*_test.js')))
    return cases


def source_hashes(root):
    # Include templates/assets and test fixtures, excluding generated bytecode.
    return {
        str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
        for folder in ('indi_allsky', 'testing')
        for p in sorted((root / folder).rglob('*'))
        if p.is_file() and '__pycache__' not in p.parts
        and p.suffix in ('.py', '.js', '.html', '.css', '.json')
        and 'evidence' not in p.relative_to(root).parts
    }


def write_report(path, report):
    pending = path.with_suffix('.tmp')
    pending.write_text(json.dumps(report, indent=2) + '\n')
    pending.replace(path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--python', default=sys.executable)
    parser.add_argument('--oauth-python', help='Interpreter with YouTube dependencies; defaults to --python')
    parser.add_argument('--node', default='node')
    parser.add_argument('--output', type=Path, help='New directory outside the source checkout')
    parser.add_argument('--timeout', type=float, default=240)
    parser.add_argument('--list', action='store_true')
    args = parser.parse_args()
    root = args.root.resolve()
    cases = discover(root, args.python, args.oauth_python or args.python, args.node)
    if args.list:
        print(json.dumps(cases, indent=2))
        return 0
    if not args.output or not 0 < args.timeout < float('inf'):
        parser.error('Provide --output and a finite positive --timeout.')
    output = args.output.resolve()
    if output == root or root in output.parents:
        parser.error('--output must be outside the source checkout.')
    for executable in {case['command'][0] for case in cases}:
        if not shutil.which(executable):
            parser.error('Interpreter is unavailable: ' + executable)
    # Never overwrite evidence from a previous run.
    output.mkdir(parents=True, exist_ok=False)
    report = {'root': str(root), 'scope': 'Automated isolated regression; not live acceptance',
              'status': 'running', 'planned': cases, 'results': [],
              'source_hashes': source_hashes(root)}
    path = output / 'results.json'
    write_report(path, report)
    try:
        for index, case in enumerate(cases):
            log = output / ('%03d.log' % index)
            started = time.monotonic()
            with log.open('w') as stream:
                try:
                    result = subprocess.run(case['command'], cwd=root, stdout=stream,
                                            stderr=subprocess.STDOUT, timeout=args.timeout)
                    code = result.returncode
                except (OSError, subprocess.TimeoutExpired) as error:
                    stream.write(str(error))
                    code = -1
            report['results'].append({**case, 'exit_code': code, 'log': str(log),
                                      'seconds': round(time.monotonic() - started, 3)})
            write_report(path, report)
            print(case['case'], 'PASS' if code == 0 else 'FAIL', flush=True)
    except KeyboardInterrupt:
        report['status'] = 'interrupted'
        write_report(path, report)
        return 130
    report['source_changed'] = source_hashes(root) != report['source_hashes']
    failed = sum(row['exit_code'] != 0 for row in report['results'])
    report['status'] = 'source_changed' if report['source_changed'] else ('failed' if failed else 'passed')
    write_report(path, report)
    print('TOTAL', len(cases), 'FAILED', failed, 'STATUS', report['status'], flush=True)
    return int(report['status'] != 'passed')


if __name__ == '__main__':
    sys.exit(main())
